---
pagetitle: Dimensional Methods
---

# Dimensional Methods {#dimmethods}

author: Fletcher, R. I.

## Preface {#dimmethods-preface}
This module is concerned with the conventional techniques such as concepts of measurement, fundamental and derived units, checking equations for dimensional consistency, and the metric system. Attention is directed almost exclusively to the dimensional necessities of scientific statements, and only incidentally to their scientific sufficiencies. The International System of Units, SI, is discussed and a problem set is used to provide practice with the metric system. The concept of dimensional homogeneity, i.e. that all terms of an equation must consist of like dimensions raised to like powers, is analyzed, and a related problem set is provided. Concepts presented in the module require knowledge of basic algebra.

## Introduction {#dimmethods-intro}

The common objective in scientific research, whatever our particular field of interest, is to discover those exact relationships that exist among the measurable quantities of nature. And typically, when our perceptions of those relationships are confirmed by experiment to have sufficient generality, we look upon our perceptions as natural laws. Although we often accept apparent truths about the natural universe that are difficult to quantify (Darwin's thesis of evolution, for example), the absolutely necessary condition for "exactness" in a scientific law is that its formulation consist of measurable quantities whose definitions depend, in turn, entirely upon a set of dimensions. In this formal sense, such classical sciences as physics and chemistry--as well as much of modern biology--are said to be exact, but obviously, some topics of natural science (such as Darwin's thesis of evolution) are characteristically inexact.

Dimensional formalities do not, of course, insure scientific infallibility. In fact, dimensionally perfect formulae sometimes turn out to be irrelevant, inaccurate, or erroneous. However, dimensional completeness fulfills the necessary condition of scientific exactness, and we cannot proceed to the more practical concerns of scientific sufficiency until we satisfy dimensional exactitude in our formulae. A scientifically sufficient formulae that is not scientifically exact is meaningless. We shall be concerned here almost exclusively with the dimensional completeness of scientific statements and only incidentally with sufficiencies. Although dimensional methods provide us with the means for determining the formally necessary relationships among the quantities of a scientific formula, we should clearly understand that experimentation, observation, empirical evidence, and insight really determine just which quantities go into the formula in the first place. 

So as to distinguish between differing *magnitudes* of a particular dimension, we must have access to a *scale* (or *unit*) of comparison. In saying "the height of that tree is nine meters" we imply that we have chosen *length* as the dimension of definition and the *meter* as the corresponding scale unit of comparison. In making the observation let us also note that "length" might have defined our concept of tallness but not necessarily our whole notion of the tree itself. This is not a trivial acknowledgment; it points up the fact that scientific definitions describe *attributes* of natural entities or occurrences, not their ontological meanings or their elemental reasons for existence. While we might employ the universal law of gravitation to quantify the attribute of attraction between bodies of mass, the law of gravitation consists wholly of dimensional relationships and tells us nothing of the "essence" of gravity, nor why every corporeal body in the universe should have a gravitational field in the first place. Although we may share an intense curiosity about such questions, their answers are usually reserved to inquiries external to science proper. Should perplexity exist over the *scientific* description of some natural quantity, its origin should be sought in the quantity's dimensional definition.

In view of these definitional objectives, we must accord to every kind of natural quantity its defining dimension, but these defining dimensions need not be wholly independent of one another. Since we desire that differing natural quantities be related through natural laws, then for simplicity and clarity of definition we should keep the number of *independent* dimensions to a minimum. This minimum set of independent dimensions we shall call *fundamental*, and all other dimensions derived from the fundamental set we shall call *derived*. Similarly, the magnitudes (the scale units) corresponding to the fundamental dimensions are viewed as fundamental magnitudes, and those corresponding to the derived dimensions as derived magnitudes. An obvious example of a derived quantity would be that of velocity--the velocity, say, of an aircraft whose pilot reads derived units of velocity magnitude directly from the scale of his airspeed indicator. Irrespective of the particular scale system on the airspeed indicator, we perceive the velocity *dimension* to be derived, in general, from the more fundamental set of dimensions, length and time, and with corresponding symbols $V$, $L$ ,$T$ we can write that general dimensional relationship as

$$[V] \equiv [\frac{L}{T}]$$

read as "the dimension $V$ is defined as the ratio of dimensions $L$ and $T$." The particular scale measurement of, say, 500 kilometers per hour would correspond to 500 derived units of velocity magnitudes derived from the kilometer and the hour. We would write the scale relationship for this particular example as

$$v = 500 \frac{km}{hr}$$

with an obvious correspondence between fundamental unit magnitudes "km" and "hr" and the fundamental dimensions $L$ and $T$. The unit symbol "$\frac{km}{hr}$" is as much a part of the value of quantity $v$ as is the numerical value "500". The conventions (the symbolic styles) employed in this example suggest the convenient fact that we can manipulate dimensional and scale symbols as algebraic entities.

There is a certain arbitrariness of choice in the number and nature of the "fundamental" dimensions, whether we are thinking of our needs in choosing dimensions for actual measurement purposes or for the more formalistic requirements of theoretical models (and there is also considerable latitude in the selection of the scale units we might regard as fundamental; those suited for one problem may not be suited for another). Because of the strong historical precedent of Newtonian mechanics, the three natural concepts of space, time, and mass are often regarded as being fundamental in the absolute sense, but, in fact, more than three fundamental dimensions are sometimes desirable, and we shall see that differing sets of fundamental dimensions can be selected, none of which need be regarded as absolutely fundamental.

## SI Units {#dimmethods-si}

In the making of scientific syntheses, our mutual needs for clear thinking and precision of meaning--as well as the need for clarity in communications between us have an obvious dependence on the exactness of our reference standards and the precision we choose to employ in the characterizing of those natural quantities that ultimately enter our formulations as symbols. Our usages here shall conform, with little revision, to the conventions and standards known as the International System of Units (abbreviated SI for *Systeme International*), supplemented where necessary by the practices of the National Bureau of Standards (NBS). In the SI system, the fundamental metric units associated with dimensions $M$, $L$, $T$ are the kilogram, the meter, and the second (customarily called the "mks system"). A variety of auxiliary metric units are employed in practice (such as the kilometer, the angstrom, the gamma, and so on), but the auxiliary or supplementary set of metric units most commonly associated with dimensions $M$, $L$, $T$ are the gram, the centimeter, and the second (customarily called the "cgs system").

The following definitions for mechanical quantities have been abstracted from publications of NBS (1964,1968) and Cray (1972). For comprehensive tabulations of the quantities appropriate to optics, acoustics, and electricity, see the *Handbook of the American Institute of Physics*, the *Handbook of Chemistry and Physics* (Chemical Rubber Co.), or the
*Handbook of the National Bureau of Standards*, which is edited and published annually.

### Fundamental Mechanical Units {#dimmethods-fundamentalunits}

*Meter*. Unit of length mks system. Symbol m, dimension L. By international agreement (1960) defined to be 1,650,763.73 wavelengths of the orange-red line of krypton 86, which replaces the length standard based on the platinum-iridium meter bar in Paris.

*Kilogram*. Unit of mass mks system. Symbol kg, dimension M. Defined to be the mass of a certain cylinder of platinum-iridium alloy, called the International Prototype Kilogram, preserved at the International Bureau of Weights and Measures in Paris. 

*Second*. Unit of time mks system. Symbol sec, dimension T. By international agreement (1960) defined to be 1/31,556,925.9747 of the tropical year 1900. (A "tropical year" is the interval of time between two successive passages of the sun through the vernal equinox.) A more recent international conference adopted provisionally a new definition of the second as the time corresponding to 9,192,631,770 oscillations of the cesium atom in the so-called atomic clock.

### Temperature Scales {#dimmethods-temperature}
In 1968 the International Committee on Weights and Measures officially adopted the "International Practical Temperature Scale", which is based on the concept of temperature (variable symbol 0, dimension 0) as being that of thermodynamic temperature. The unit magnitude of the International Scale is the degree Kelvin (symbol K). The degree Kelvin is the fraction 1/273.16 of the triple point of water. The Celsius temperature scale is defined in terms of the Kelvin scale as
$$\theta_c=\frac{1^{\circ}C}{1K}\Big(\theta_k-\theta_0\Big)$$
where $\theta_c$ is the temperature magnitude on the Celsius scale, $\theta_k$ the temperature magnitude on the Kelvin scale, and $\theta_0$ = 273.15K (the ice point of water). The scale unit of the Celsius temperature is the degree Celsius (symbol $^{\circ}$C), equal in magnitude to the degree Kelvin. Reference point relationships between Kelvin, Celsius, and Fahrenheit scales are:  

 *  0K = -273.15 $^{\circ}$C = -459.67$^{\circ}$F ("absolute" zero),  
 *  273.15K = 0$^{\circ}$C = 32$^{\circ}$F (the ice point),  
 *  273.16K = 0.01$^{\circ}$C = 32.018$^{\circ}$F (equilibrium between solid, liquid, and vapor phases of water; the triple point),  
 *  373.15K = 100$^{\circ}$C = 212$^{\circ}$F (the boiling point of water).

The relationships between the Kelvin, Celsius, and Fahrenheit scales are linear and appear as straight lines when graphed.


### Supplementary Mechanical Units {#dimmethods-suppunits}
*Centimeter*. Unit of length cgs system. Symbol cm, dimension L. Defined to be 1/100 meter.

*Gram*. Unit of mass cgs system. Symbol g, dimension M. Defined to be 1/1000 kilogram.

*International Yard*. Unit of length. Symbol yd, dimension L. Defined by agreement between the United States and the British Commonwealth (1959) to be 0.9144 meter.

*International Pound*. Unit of mass. Symbol lb, dimension M. Defined by agreement between the United States and the British Commonwealth (1959) to be 0.45359237 kilogram.

*Angstrom*. Unit of length. Symbol $\mathring{A}$, dimension L. Defined to be 10$^{-8}$ cm. Gamma. See microgram.

*Microgram*. Unit of mass. Symbol $\mu$g, dimension M. Defined to be 10$^{-6}$ g. 

*Micrometer*. Unit of length. Symbol $\mu$m, dimension L. Defined to be 10$^{-6}$ m (1/1000 cm). Equivalent to, but replaces, micron (symbol $\mu$).

*Micron*. See micrometer.

### Angular Units  {#dimmethods-angularunits}
*Degree*. Unit of angular measure. Symbol deg or $^{\circ}$ (superscript), dimensionless, Defined as the angle subtended at the center by a circular arc 1/360 the circumference.

*Radian*. Unit of angular measure. Symbol radian, dimensionless. Defined as the angle subtended at the center by a circular arc equal in length to the radius of the circle. 1 radian = 360/2$\pi$ degrees angular measure.

### Derived Units  {#dimmethods-derived}
*Atmosphere*. Unit of pressure. Symbol atm, dimension FL$^{-2}$ or ML$^{-1}$T$^{-2}$. Defined to be the pressure exerted by dry atmosphere, 0$^{\circ}$C, at mean sea level. Equivalent to $1.013250 \times 10^6 dyn\cdot cm^{-2}$ in cgs units.

*Bar*. Unit of pressure. Symbol bar, dimension FL$^{-2}$ or ML$^{-1}$T$^{-2}$. Equal to $10^5 nt\cdot m^{-2}$ in mks units.

*British Thermal Unit (Mean)*. Unit of energy or quantity of heat. Symbol Btu, mechanical dimension ML$^2$T$^{-2}$, thermal dimension H. Originally defined to be the quantity of heat energy required to raise the temperature of 1 lb mass of water 1$^{\circ}$F (averaged from 32$^{\circ}$F to 212$^{\circ}$F). Equivalent to 252.16038 gram calories.

*Calorie (Mean)*. Unit of energy or quantity of heat. Symbol cal, mechanical dimension ML$^2$T$^{-2}$, thermal dimension H. Originally defined to be the quantity of heat energy required to raise the temperature of 1 g mass of water 1$^{\circ}$C (averaged from 0$^{\circ}$C to 100$^{\circ}$C). Equivalent to 4.1840 joules.

*Dyne*. Unit of force cgs system. Symbol dyn, dimension F or MLT$^{-2}$, unit g$\cdot$cm$\cdot$sec$^{-2}$. Force required to give 1 g mass an acceleration of 1 cm$\cdot$sec$^{-2}$.

*Erg*. Unit of work or energy cgs system. Symbol erg, dimension FL or ML$^2$T$^{-2}$, unit dyn$\cdot$cm or g$\cdot$cm$^2\cdot$sec$^{-2}$. Work done by a force of 1 dyne acting through a distance of 1 cm (10$^7$ erg = 1 J).

*Hertz*. Unit of frequency. Symbol Hz, dimension T$^{-1}$, unit sec$^{-1}$. Equivalent to, but replaces, unit cps (cycle per second).

*Joule*. Unit of work or energy mks system. Symbol J, dimension FL or ML$^2$T$^{-2}$, unit ntm or kg$\cdot$m$^2\cdot$sec$^{-2}$. The work done by a force of 1 newton acting through a distance of 1 meter.

*Liter*. Unit of volume (liquids and gases). Symbol 1, dimension L$^3$. Originally defined to be the volume of 1 kg airfree $H_2O$ at 4$^{\circ}$C (the maximum density temperature of water). Redefined by international agreement (1964) to be 1/1000 cubic meter (10$^{-3}$m$^3$) exactly.

*Newton*. Unit of force mks system. Symbol N (alternate symbol nt), dimension F or MLT$^{-2}$. Force required to give 1 kg mass an acceleration of 1 m$\cdot$sec$^{-2}$.

*Poise*. Unit of viscosity cgs system. Symbol P, dimension FL$^{-2}$T or ML$^{-1}$T$^{-1}$, unit dyn$\cdot$cm$^{-2}\cdot$sec or g$\cdot$cm$^{-1}\cdot$sec$^{-1}$. Shear viscosity, or resistance to flow, is defined as the ratio of shearing stress (tangential force per unit area) in a moving fluid and its associated rate of area deformation ($dA/Adt$). Shear viscosity is sometimes called the dynamic viscosity.

*Poundal*. Unit of force. Symbol lbf (pound force), dimension F or MLT$^{-2}$. Force required to give 1 lb mass an acceleration of 1 ft$\cdot$sec$^{-2}$.

*Stokes*. Unit of kinematic viscosity cgs system. Symbol St, dimension L$^2$T$^{-1}$, unit cm$^2\cdot$sec$^{-1}$. Kinematic viscosity in units of Stokes is defined to be the ratio of the dynamic viscosity (in poise) of a fluid to its cgs density (g$\cdot$cm$^{-3}$).

*Torr*. Unit of pressure. Symbol torr, dimension FL$^{-2}$ or ML$^{-1}$T$^{-2}$. The pressure exerted by a column of mercury 1 mm in height, 0$^{\circ}$C. Equivalent to 13.3322 dyn$\cdot$cm$^{-2}$ in cgs units.

*Watt*. Unit of power or rate of work mks system. Symbol W, dimension FLT$^{-1}$ or ML$^2$T$^{-3}$, unit J$\cdot$sec$^{-1}$ or nt$\cdot$m$\cdot$sec$^{-1}$ or kg$\cdot$m$^2\cdot$sec$^{-3}$. Work done or energy expended at the rate of l J$\cdot$sec$^{-1}$.


An appendix summarizing the SI units and dimensions is attached.


### Auxiliary Prefixs of the Metric System {#dimmethods-auxprefixes}

| Multiples and sub-multiples  | Prefix |
|:---------------------------:|:------:|
|           10^-18^           |  atto  |
|           10^-15^           |  femto |
|           10^-12^           |  pico  |
|            10^-9^           |  nano  |
|            10^-6^           |  micro |
|            10^-3^           |  milli |
|            10^-2^           |  centi |
|            10^-1^           |  deci  |
|              10             |  deka  |
|            10^2^            |  hecto |
|            10^3^            |  kilo  |
|            10^6^            |  mega  |
|            10^9^            |  giga  |
|            10^12^           |  tera  |

## Dimentional Homogeneity {#dimmethods-homogeneity}

Should we reduce to its fundamental dimensions each of the quantities occurring in a valid physical equation, all *terms* of the equation must then consist of like fundamental dimensions raised to like powers. The equation must be *dimensionally homogeneous*. This is a truism for definitional equations, and for those equations of empirical basis it expresses a condition of physical necessity. The principle of dimensional homogeneity, or its equivalent, is the basic axiom for the operational rules in the general method of *dimensional analysis*.

### The Dimentional Constraints on Definitional and Empirical Equations {#dimmethods-constraints}

The principle of homogeneity applies to equations of purely dimensional content, and it applies to equations that contain scale magnitudes and quantities of measurement. It excludes any equation that might be mathematically complete but physically meaningless. For example, the equation

$$x + y = z$$

where $x + y$ sums to a quantity $z$, is mathematically correct for numbers. But let $x$ and $y$ have dimensional content. Let $x$, say, be the displacement of a uniformly accelerated body starting from rest, and let $y$ be its velocity over time. Accordingly,
$$y=at\;\mbox{, }\;x=\frac{1}{2}at^2$$
$a$ being the uniform acceleration and $t$ the time variable. Our mathematically complete equation becomes
$$z=\frac{1}{2}at^2+at$$
which is physically meaningless since we have attempted to sum incompatible natural quantities (displacement and velocity). By reducing each term on the RHS to its fundamental dimensions, the violation of the homogeneity principle becomes obvious. Since $[a] = LT^{-2}$, then
$$[\frac{1}{2}at^2]=LT^{-2}T^2=L$$
$$[at]=LT^{-2}T=LT^{-1}$$
and obviously, the terms do not reduce to like dimensions.

Now let us suppose $x$ and $y$ to be some measured magnitudes of a body, say its length $x$ = 1 meter and its mass $y$ = 3 kilograms. By the definitions 1 m = 100 cm and 3 kg = 3000 g, we can write, in good mathematical faith,
$$1m + 3kg = 100cm + 3000g$$
or even
$$1m - 3000g = 100cm - 3kg$$
Terms on opposing sides are nicely balanced in the algebraic sense, but what does it mean to subtract 3000 grams of mass from 1 meter of length? The dimensions of the terms in the equation are
$$[1m]=[100cm]=L$$
$$[3kg]=[3000g] =M$$
and the homogeneity principle is again violated; we must reject the equation (and others like it) as having no physical significance. Common sense, of course, would lead us to such distinctions in the first place.

The assignment of dimensions to the elements of integrals, differential equations, difference equations, and integro-differential equations is just as straightforward (but perhaps not so obvious) as that of simple algebraic structures. For expositional purposes, let the symbol "$X$" in the following examples be the dimension of the quantity $x$:  
Differentials:  
\begin{align*}
&[dx]=X \\
&[d^2x] = X \\
&[dx^2] = X^2 \\
\end{align*}

Differential operators:  
\begin{align*}
&\Big[\frac{d}{dx}\Big]=X^{-1} \\
&\Big[\frac{dM}{dx}\Big]=[M]X^{-1} \\
&[\dot{x}]=\Big[\frac{dx}{dt}\Big]=XT^{-1} \\
&\Big[\frac{d^n}{dx^n}\Big]=X^{-n}\; \mbox{ (n a positive integer)} \\
&\Big[\frac{d^nM}{dx^n}\Big]=[M]X^{-n} \\
\end{align*}

\begin{align*}
&[\ddot{x}]=\Big[\frac{d^2x}{dt^2}\Big]=XT^{-2} \\
&\Big[\frac{\partial}{\partial x}\Big]=X^{-1} \\
&\Big[\frac{\partial M}{\partial x}\Big]=[M]X^{-1} \\
&\Big[\frac{\partial^n}{\partial x^n}\Big]=X^{-n} \\
&\Big[\frac{\partial^n M}{\partial x^n}\Big]=[M]X^{-n} \\
\end{align*}

Laplacian:  
\begin{align*}
&[\nabla\phi]=\bigg[\frac{\partial^2\phi}{\partial x^2}+\frac{\partial^2\phi}{\partial y^2}+\frac{\partial^2\phi}{\partial z^2}\bigg]=[\phi]L^{-2}\;\;\mbox{each term}
\end{align*}

Difference operators:  
\begin{align*}
&[\Delta x]=X \\
&[\Delta^2x]=X \\
&[\Delta^n x]=X \\
\end{align*}

Indexed differences:  
\begin{align*}
&[x_{i+1}-x_i]=X
\end{align*}

Indefinite integrals:  
\begin{align*}
&\bigg[\int f(x)dx\bigg]-[f(x)]X \\
&\bigg[\int\!\!\!\int f(x,y)dxdy\bigg]=[f(x,y)][dy][dx]=[f(x,y)][y]X \\
\end{align*}

Definite integrals:  
\begin{align*}
&\bigg[\int_xf(t)dt\bigg]=[f(x)]X \\
&\bigg[\int\!\!\!\int_Rf(x,y)dxdy\bigg]=\bigg[\int_{y_1}dy\int_{x_1}[f(x,y)dx\bigg]=[f(x_1,y_1)][dy_1][dx_1]
\end{align*}

Let us use the following integro-differential equation to illustrate the homogeneity of analytical equations that have physical meaning. The equation arises from the principle of momentum conservation as applied to the two-dimensional steady flow of a viscous fluid at a boundary. The quantities $u$, $U$ are velocities, while $x$, $y$ are the two-dimensional space variables of displacement, and $v$ is the kinematic viscosity of the fluid:
$$u\frac{\partial u}{\partial x}-\frac{\partial u}{\partial y}\bigg[\frac{\partial}{\partial y}\int_0^yudy\bigg]=U\frac{dU}{dx}+x\frac{\partial^2u}{\partial y^2}$$
The terms of the equation separately reduce to fundamental dimensions as follows. Note that the dimensional set {$L,V$} accommodates this equation equally as well as the set {$L,T$}.

\begin{align*}
&\Big[u\frac{\partial u}{\partial x}\Big]=V\frac{V}{L}=LT^{-1}LT^{-1}L^{-1}=LT^{-2} \\
&\Big[\frac{\partial u}{\partial y}\Big(\frac{\partial}{\partial x}\int_0^yudy\Big)\Big]=\Big[\frac{\partial u}{\partial y}\Big]\Big[\frac{\partial}{\partial x}\Big]\Big[u(y)\Big]\Big[dy\Big] \\
&= \frac{V}{L}\frac{1}{L}VL=LT^{-1}L^{-1}LT^{-1}L=LT^{-2} \\
&\Big[U\frac{dU}{dx}\Big]=LT^{-1}LT^{-1}L^{-1}=LT^{-2} \\
&\bigg[v\frac{\partial^2u}{\partial y^2}\bigg] = L^2T^{-1}\frac{LT^{-1}}{L^2} LT^{-2} \\
\end{align*}

Hence, our equation is dimensionally homogeneous; its dimensions are those of acceleration. We can also write the dimensions of any term as
$$LT^{-2}=\frac{MLT^{-2}}{M}=\frac{F}{M}$$
which are the dimensions of force per unit mass (of fluid).

### Intensive and Extensive Properties {#dimmethods-properties}
Properties that depend on the total quantity of matter (or total effect) being measured are called **extensive** properties. If we take twice as much matter of a given substance, for example, it will contain twice as much volume and twice as much mass, implying that mass and volume are to be regarded as extensive properties of a substance. Properties independent of the quantity of matter or total effect being measured are called **intensive** properties. The density of a substance and its temperature are examples of the intensive properties of the substance. The density of water, say, is the same--under similar conditions--whether we measure one cupful or one cubic kilometer. Intensive properties are properties of the substances themselves, and, like the density of water, can be used in the identification of a substance, since, generally speaking, unlike substances differ in their intensive properties. The name of an intensive property will often bear the prefix "specific". Examples are specific volume (the volume occupied by a unit mass of a substance) and specific luminous intensity (the luminous intensity per unit area of source).

Physical equations often contain a mixture of intensive and extensive quantities, but the principle of dimensional homogeneity still holds. When multiplied by density $\rho$, for example, our last sample equation becomes
$$\rho u\frac{\partial u}{\partial x}-\rho \frac{\partial u}{\partial y}\bigg[\frac{\partial}{\partial x}\int_0^yudy\bigg]=\rho U\frac{dU}{dx}+\mu\frac{\partial^2u}{\partial y^2}$$
where $\mu$ is now the dynamic viscosity of the fluid [$v \equiv \mu/\rho$] being the definition of kinematic viscosity]. By dimensional reduction, the first term becomes
$$\Big[\rho u\frac{\partial u}{\partial x}\Big]=ML^{-3}LT^{-1}LT^{-1}L^{-1}=ML^{-2}T^{-2}$$
which, of course, is typical of all the terms. We can also write the term dimensions of each term as
$$ML^{-2}T^{-2}=MLL^{-3}T^{-2}=\frac{MLT^{-2}}{L^3}=\frac{F}{L^3}$$
which are the dimensions of force per unit volume (of fluid).

### Conversion Factors {#dimmethods-conversion}
Very often the magnitude of a quantity must be transformed from one set of scale units to a different set of scale units (pounds to grams, miles per hour to meters per second, and so on). Such a transformation is commonly called a conversion of units, and conversions between two units can be made whenever the two units have the same dimensions (pounds and grams both have dimension $M$, miles per hour and meters per second both have dimensions $LT^{-1}$, and so on), and whenever we know the equation (the identity) that relates the two units. To convert, say, the magnitude of the mass of some object from units of pounds to units of kilograms, we make use of the identity
$$1 lb=0.45359237kg$$
or the identity
$$1kg=2.2046226lb$$
(where the number of significant figures we actually choose to employ depends, of course, on the accuracy appropriate to the application). From the first identity we can write the conversion factor
$$\frac{0.45359237kg}{1lb}=1$$
and from the second we can write the conversion factor
$$\frac{2.2046226lb}{1kg}=1$$
In either case, the factor is dimensionless and equal to unity. *Any conversion factor is a dimensionless ratio of scale units identically equal to unity.*

For the sake of illustration, let us transform 4.2 pounds scale magnitude of mass to the equivalent magnitude in units of the kilogram. We start by making the obvious statement
$$4.2lb=4.2lb$$
and then operate on the RHS with the appropriate conversion factor. Since we want "lb" to cancel on the RHS (leaving "kg"), we choose the factor that has "lb" in the denominator:
$$4.2lb=4.2\rlap{---}lb\bigg(\frac{0.454kg}{1\rlap{---} lb}\bigg)$$
Perform the necessary multiplication and get
$$4.2lb=1.907kg$$
We follow much the same procedure for conversions that require a combination of conversion factors. Suppose we desire to have the scale velocity of 30 miles per hour in units of the centimeter and the second. Accordingly, we are concerned here with essentially two chains of conversions, one for dimension L and one for dimension T. 

L: mile $\rightarrow$ foot $\rightarrow$ inch $\rightarrow$ centimeter.  
T: hour $\rightarrow$ minute $\rightarrow$ second.  

We write the required identities and apply them one by one.

For dimension L:  
&nbsp;&nbsp;&nbsp;&nbsp;Identity: 1 mi = 5280 ft  
&nbsp;&nbsp;&nbsp;&nbsp;Conversion factors: $\frac{5280 ft}{1mi}=1$ or $\frac{1mi}{5280ft}=1$  
&nbsp;&nbsp;&nbsp;&nbsp;Identity: 1 ft = 12 in  
&nbsp;&nbsp;&nbsp;&nbsp;Conversion factors: $\frac{12in}{1ft}$ or $\frac{1ft}{12in}=1$  
&nbsp;&nbsp;&nbsp;&nbsp;Identity: 1 in = 2.54 cm  
&nbsp;&nbsp;&nbsp;&nbsp;Conversion factors: $\frac{2.54cm}{1in}=1$ or $\frac{1in}{2.54cm}=1$

For dimension T:  
&nbsp;&nbsp;&nbsp;&nbsp;Identity: 1 hr = 60 min  
&nbsp;&nbsp;&nbsp;&nbsp;Conversion factors: $\frac{60min}{1hr}=1$ or $\frac{1hr}{60min}=1$  
&nbsp;&nbsp;&nbsp;&nbsp;Identity: 1 min = 60 sec  
&nbsp;&nbsp;&nbsp;&nbsp;Conversion factors: $\frac{60sec}{1min}=1$ or $\frac{1min}{60sec}=1$  
To proceed with the conversion we make the obvious statement
$$\frac{30mi}{1hr}=\frac{30mi}{1hr}$$
and convert the units for each dimension. Starting with L (as a matter of choice; we could start with T just as legitimately), we follow the chain mile $\rightarrow$ foot $\rightarrow$ ..., and employ the conversion factor that cancels the unit "mi":
$$\frac{30mi}{1hr}=\frac{30 \rlap{-----}mi}{1hr}\Big(\frac{5280ft}{1\rlap{-----}mi}\Big)$$
We continue the process and arrive at the unit "cm":
$$\frac{30mi}{1hr}=\frac{30 \rlap{-----}mi} {1hr}\Big(\frac{5280\rlap{----}ft} {1\rlap{-----}mi}\Big)\Big(\frac {12\rlap{---}in}{1\rlap{----}ft}\Big)\Big(\frac{2.54cm}{1\rlap{---}in}\Big)$$
Now we complete the process for units of T. Again we follow the, appropriate conversion chain (hour $\rightarrow$ minute $\rightarrow$ ...). Since "hr" appears in a denominator, we choose the hr $\rightarrow$ min conversion that will cancel "hr", and so on:
$$\frac{30mi}{1hr}=\frac{30}{1\rlap{----}hr}\Big(\frac{5280}{1}\Big)\Big(\frac{12}{1}\Big)\Big(\frac{2.54}{1}\Big)\Big(\frac{1\rlap{----}hr}{60\rlap{------}min}\Big)\Big(\frac{1\rlap{------}min}{60sec}\Big)$$
And finally, we perform the necessary multiplication and get the desired conversion
$$30mi/hr=1340cm/sec$$
The rational operations of algebra extend with great convenience to the operations (and conversions) on scale units. 

Example.  
Convert the area magnitude of 1 square inch to units of square centimeters:  
The identity between the inch and the centimeter is
$$1in=2.54cm$$
and by squaring both sides of the identity we get
\begin{align*}
(1in)^2&=(2.54cm)^2 \\
&=(2.54)^2cm^2 \\
1in^2&=6.4516cm^2 \\
\end{align*}

Example. Convert 20 in^2^ to units of cm^2^:  
Make the obvious statement
$$20in^2=20in^2$$
From the previous example we can write the conversion factor
$$\frac{6.4516cm^2}{1in^2}=1$$
and thus
$$20in^2=\frac{20\rlap{---}in^2}{1}\Big(\frac{6.4516cm^2}{1\rlap{---}in^2}\Big)$$
$$20in^2=129.032cm^2$$

Example. The density of CCl~4~ at 0$^{\circ}$C is 1.600 grams per cubic centimeter. Convert this intensive property to units of the ounce and the cubic inch:  
The units to be converted have dimensions M and L^3^. The chains of conversions are  

M: gram $\rightarrow$ pound $\rightarrow$ ounce,  
L^3^: cm^3^ $\rightarrow$ in^3^  

Identities and conversion factors are  
&nbsp;&nbsp;&nbsp;&nbsp;gram $\rightarrow$ pound:  
&nbsp;&nbsp;&nbsp;&nbsp;1 lb = 453.6 g &nbsp;&nbsp;or &nbsp;&nbsp;2.205 lb = 100 g (since 1 kg = 100 g),  
&nbsp;&nbsp;&nbsp;&nbsp;$\frac{453.6g}{1lb}=1$ &nbsp;&nbsp;or &nbsp;&nbsp;$\frac{1lb}{453.6g} =1$ &nbsp;&nbsp;or &nbsp;&nbsp;$\frac{2.205lb}{100g}=1$ &nbsp;&nbsp;or &nbsp;&nbsp;$\frac{100g}{2.205lb}$.  
&nbsp;&nbsp;&nbsp;&nbsp;pound $\rightarrow$ ounce:  
&nbsp;&nbsp;&nbsp;&nbsp;16 oz = 1 lb  
&nbsp;&nbsp;&nbsp;&nbsp;$\frac{16oz}{1lb}=1$ &nbsp;&nbsp;or &nbsp;&nbsp;$\frac{1lb}{16oz}=1$.  
&nbsp;&nbsp;&nbsp;&nbsp;cm^3^ $\rightarrow$ in^3^:  
&nbsp;&nbsp;&nbsp;&nbsp;1 in = 2.54 cm  
&nbsp;&nbsp;&nbsp;&nbsp;1 in^3^ = 16.387 cm^3^,  
&nbsp;&nbsp;&nbsp;&nbsp;$\frac{16.387cm^3}{1in^3}=1$ &nbsp;&nbsp;or &nbsp;&nbsp;$\frac{1in^3}{16.387cm^3}=1$.

Make the obvious statement
$$\frac{1.600g}{1cm^3}=\frac{1.600g}{1cm^3}$$
Apply the chain of conversion factors, choosing those that cancel in succession:
$$\frac{1.600g}{1cm^3}=\frac{1.600\rlap{--}g}{1\rlap{-----}cm^3}\Big(\frac{1\rlap{---}lb}{453.6\rlap{--}g}\Big)\Big(\frac{16oz}{1\rlap{---}lb}\Big)\Big(\frac{16.387\rlap{-----}cm^3}{1in^3}\Big)$$
$$1.600g\cdot cm^{-3}=0.9248oz\cdot in^{-3}$$
which is the desired conversion.

## Problem Set {#dimmethods-problems}

PROBLEM SET 1

1. Employ the dimensional set $M$ (mass), $V$ (velocity), $T$ (time), and do the following exercise. The attached solutions may be consulted if necessary.  
    (a) The linear acceleration of a particle can be envisioned as the increase or decrease in the velocity of the particle, measured over a short time period. Write the dimensions of linear acceleration.  
    (b) The magnitude of force on a body wholly free to move can be calculated as the product of the body's mass and its linear acceleration. Write the dimensions of mechanical force.  
    (c) The instantaneous kinetic energy of a moving body is proportional to the mass of the body and to the square of its linear speed. Write the dimensional formula for kinetic energy.

2. Employ the dimensional set $M$ (mass), $L$ (length), $T$ (time), and do (a), (b), (c) of Exercise 1.

3. Employ the dimensional set $F$ (force), $L$ (length), $T$ (time), and do the following exercise.  
    (a) Problem (c) of Exercise 1.  
    (b) The work done in moving the body of Problem 1(c) is equivalent to the product of the force acting on the body and the distance the body moves while the force is being applied. Write the dimensional formula for mechanical work.  
    (c) Power is defined as the time rate of energy expenditure (or, equivalently, as the rate at which work is done). Write the dimensional formula for the power of the agency that imparts the motion to the body of Problem 3(b).
    
4. Employ the dimensional set $M$, $L$, $T$ and do (b), (c) of Exercise 3.

5. In the mks system of measurement, the meter (m) is the unit standard of length, the kilogram (kg) the unit standard of mass, and the second (sec) the unit standard of time. The derived unit of force in the mks system is called the "newton" (nt), the derived unit of energy is called the "joule", and the derived unit of power is called the "watt". Employ the mks system of measurement and write the unit magnitudes of the corresponding quantities described in Exercises 2, 3, 4.

PROBLEM SET 2

1. Determine the number of 24-hour days in the tropical year 1900.

2. Write algebraic formulae for the relationships between  
    (a) Kelvin and Fahrenheit temperature,  
    (b) Celsius and Fahrenheit temperature.
3. A molecule of water occupies a square cross-sectional area of about 10 $\mathring{A}^2$. How many water molecules are needed to cover a square centimeter of surface?

4. Determine the kinetic energy in ergs of a molecule having a mass of $2.0\times10^{-22}$g and a velocity of $4.0\times10^4$cm$\cdot$sec^-1^.

5. A red blood cell has a diameter of 7.5 microns; express its diameter in units of centimeter length.

6. Write as ordinary magnitudes of the units indicated:  
    (a) 3.5 milliliters of benzine
    (b) 3.5 deciliters of seawater
    (c) 1 kiloyear of Roman Empire
    (d) 0.04 megawatts of electrical power
    (e) 2 nanograms of a butterfly's breakfast
    (f) 0.002 nanograms of proton mass
    (g) 200.5 picograms of hydronium ion
    (h) 1.099 micromoles of H~2~SO~4~
    (i) 1 hectare of rice paddy
    (j) 10 square dekacentimeters of contiguous quadrat

7. Express the following quantities with appropriate metric prefixes:  
    (a) 7.35 $\times$ 10^9^ liters
    (b) 7.35 $\times$ 10^-9^ liters
    (c) 1,000,000 watts
    (d) 0.20 $\times$ 10^-5^ moles
    (e) 8,575,000 microcuries
    (f) 2.10 $\times$ 10^3^ calories per gram
    (g) 10^-3^ photons/cm^2^
    
PROBLEM SET 3

1. Determine the dimensions of the following:  
    (a)$\int_{x_1}^{x_2}mv(x)dv$, where $m$ is the mass of a body and $v$ its velocity along a path from $x_1$ to $x_2$.  
    (b)$\frac{\partial}{\partial x}\int mvdv$  
    (c)Given $R=\mu\int_xf(t)dt$, determine the dimensions of $f(x)$ where $R$ stands for frictional resistance, $\mu$ is dynamic viscosity, and $x$ is the Cartesian variable of location.

2. Given the Poisson equation $\nabla^2\phi=f(x,y)$, where $f(x,y)$ describes the distribution in a membrane of the ratio of load (force) per unit area to the tension (force) per unit length, determine the dimensions of the potential function $\phi(x,y)$.

3. Given the equation of motion $\ddot{x}+\omega^2x=f(t)$, determine the dimensions of $\omega$ and $f(t)$, where $x$ is the measure of displacement.

4. Show that the equation 
$$-\rho\frac{\partial p}{\partial z}+\mu\frac{\partial^2\omega} {\partial z^2}=0$$
is not correctly formulated, irrespective of its intended meaning, where $\rho$ is fluid density, $p$ is pressure, $\mu$ is dynamic viscosity, $\omega$ is fluid velocity, and $z$ is the Cartesian dimension of displacement.

5. Employ the dimensions $H$ (quantity of heat), $\Theta$ (temperature), and $M$ (mass).  
    (a) Write the dimensional formula for specific heat, which is defined as the quantity of heat required to impart a unit increase in temperature to a unit mass of substance.  
    (b) Formulate a scale unit of specific heat in terms of the gram, the degree Kelvin, and the calorie.

6. In many circumstances, the transfer of heat by conduction can be described by Fourier's law
$$\vec{q}=-k\nabla\theta$$
where $\vec{q}$ is the vector of heat current density (quantity of heat per unit area per unit time), $\nabla\theta$ the temperature gradient vector, and $k$ the *coefficient of thermal conductivity* (whose magnitude depends on the nature of the conducting substance). Expand the equation into its component parts and do the following problems.  
    (a) Employ the dimensional set {$H$, $\Theta$, $L$, $T$} and write the dimensional formula for the coefficient of thermal conductivity. Define $k$ in words.
    (b) Employ the calorie, degree Celsius, centimeter, and second; write a scale unit for $k$.  
    (c) Employ the joule, degree Kelvin, meter, and second; write a scale unit for $k$.  
    (d) Employ the dimensional set {$M$, $\Theta$, $L$, $T$} and write the dimensional formula for the mechanical equivalent of $k$.  
    (e) Employ the gram, centimeter, degree Kelvin, and second; write a scale unit for $k$.  
    (f) Employ the dimensional set {$F$, $\Theta$, $L$, $T$} and write a dimensional formula for $k$.  
    (g) Employ the newton, degree Kelvin, and second; write a scale unit for $k$.  
    (h) Employ the watt, meter, and degree Kelvin; write a scale unit for k.  
    (i) Write a conversion factor between your units of (b) and (c).  
    (j) Write a conversion factor between your units of (c) and (e).

7. Determine the volume in cubic centimeters of a sphere of radius 1.5 ft.

8. The density of grain alcohol at 20$^{\circ}$C is 0.79 g$\cdot$cm^-3^. Determine the mass of 30 ml of alcohol.

9. The blade of an ice skate makes contact with the ice over a length of about 15 cm and a width of 2.8 mm. Calculate the pressure on the ice produced by an ice-skater of 150 lbs mass. [The acceleration of gravity at the earth's surface is about 980 cm$\cdot$sec^-2^.]

10. A phonograph needle makes contact with a record surface over a circular area of diameter 80 $\mu$m. Calculate the pressure on the record when the needle arm weighs 2 ounces.

## Answers and Solutions {#dimmethods-answers}

PROBLEM SET 1  

1(a) $VT^{-1}$  
&nbsp;(b) $MVT^{-1}$  
&nbsp;(c) $MV^2$  
2(a) $LT^{-2}$ (by substituting $LT^{-1}$ for $V$).  
&nbsp;(b) $MLT^{-2}$  
&nbsp;(c) $ML^2T^{-2}$  
3(a) $FL$  
&nbsp;(b) $FL$  
&nbsp;(c) $FLT^{-1}$  
4(b) $ML^2T^{-2}$  
&nbsp;(c) $ML^2T^{-3}$  
5. 2(a) 1 m$\cdot$sec^-2^  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(b) 1 kg$\cdot$m$\cdot$sec^-2^  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(c) 1 kg$\cdot$m^2^$\cdot$sec^-2^  
&nbsp;&nbsp;&nbsp;3(a) 1 nt$\cdot$m, or 1 joule  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(b) 1 nt$\cdot$m, or 1 joule  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(c) 1 nt$\cdot$m$\cdot$sec^-1^, or 1 joule$\cdot$sec^-1^, or 1 watt  
&nbsp;&nbsp;&nbsp;4(b) 1 kg$\cdot$m^2^$\cdot$sec^-2^, or 1 nt$\cdot$m, or 1 joule  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(c) 1 kg$\cdot$m^2^$\cdot$sec^-3^, or 1 nt$\cdot$m$\cdot$sec^-1^, or 1 joule$\cdot$sec^-1^, or 1 watt

PROBLEM SET 2

1. Given $1 sec=\frac{1}{31,556,925.9747}$trop.yr  
31,556,925.9747 sec = 1 trop.yr  
and since 1 solar day (24 hrs) = 86400 sec, then  
$$(31556925.9747 sec)\frac{1\mbox{ solar day}}{86400 sec}=1\mbox{ trop.yr}$$
365.2422 solar days = 1 trop.yr

Note: The *sidereal* year is the time required for the sun to go once around the ecliptic and resume its (apparent) original position among the stars. The sidereal year is 365.2564 mean solar days. The tropical and sidereal years would be of equal durations were it not for precession of the equinoxes, an effect owed primarily to the moon.

2.
(a) $\theta_k=\frac{5K}{9^{\circ}F}\theta_f+255.37K$  
(b) $\theta_c=\frac{5^{\circ}C}{9^{\circ}F}\theta_f-17.78^{\circ}C$

3. By letting $n$ be the number of molecules and a the area of each molecule, we want $n\cdot a$ to be 1 square cm of area:
$$n\cdot a=1cm^2$$
We are given $a=10\mathring{A}^2$, and knowing that $1\mathring{A}=10^{-8}cm$, then 
$$a=10\mathring{A}^2=10(10^{-8}cm)^2=10\times10^{-16}cm^2=10^{-15}cm^2$$
whence, by the first equation,
$$n=\frac{1cm^2}{a}=\frac{1cm^2}{10^{-15}cm^2}=10^{15}$$
a pure number since the units (cm^2^/cm^2^) cancel.

4.

\begin{align*}
K.E. &= \frac{1}{2}mv^2 \\
&=\frac{1}{2}(2.0\times10^{-22}g)(4.0\times10^4cm\cdot sec^{-1})^2 \\
&=(1.0\times10^{-22}g)(16.0\times10^8cm^2\cdot sec^{-2}) \\
&=1.0\times16.0\times10^{-22}\times10^8g\cdot cm^2\cdot sec^{-2} \\
&=1.6\times 10^{-13}erg
\end{align*}

5. 1 micron = 10^-6^m [but 1 m = 10^2^ cm]  
= 10^-6^(10^2^ cm)  
= 10^-4^ cm  
7.5 microns = 7.5 $\times$ 10^-4^ cm

6.
(a) $3.5\times10^{-3}l = 0.0035l$  
(b) $3.5\times10^{-1} l = 0.35l$  
(c) $10^3yr=1000yr$  
(d) $0.04\times10^6W=4\times10^4W=40000W$  
(e) $2\times10^{-9}g=0.000000002g$  
(f) $0.002\times10^{-9}g=2\times10^{-12}g$  
(g) $200.5\times10^{-12}g=2.005\times10^{-10}g$  
(h) $1.099\times10^{-6}mol$  
(i) $10^2are=100are$ [1 are = 100 m^2^, hence 1 hectare = 10000 m^2^]  
(j) $10 (dekacm)^2=10(10^2cm^2)=10^3cm^2=1000cm^2$, or, in meters  
$10(dekacm)^2= 10(10\times10^{-2}m)^2 =10(10^{-1}m)^2=10(10^{-2}m^2) =10^{-1}m^2=0.1m^2$

7.
(a) 7.35 gigaliters  
(b) 7.35 nanoliters  
(c) 1 megawatt  
(d) 0.20 $\times$ 10^-5^ mol = 2.0 $\times$ 10^-6^ mol = 2.0 micromoles  
(e) 8.575 megamicrocuries = 8.575 (10^6^$\cdot$ 10^-6^ curies) = 8.575 curies  
(f) 2.10 kilocalories per gram = 2.10 Kcal$\cdot$ g^-1^  
(g) 1 milliphoton/cm^2^ = 1 mphot$\cdot$cm^-2^  

PROBLEM SET 3

1. 
(a) $[m][v(x)][dv]=MV^2$ (dimensions of kinetic energy), or $MV^2=M(LT^{-1})^2=ML^2T^{-2}=FL$ (the dimensions of mechanical work).  
(b) $\Big[\frac{\partial}{\partial x}\Big][m][v][dv]=\frac{MV^2}{L}=MLT^{-2}=F$  
(c) $[R]=[\mu][f(x)][dx]$, whence  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$[f(x)]=\frac{[R]}{[\mu][dx]}$, and since frictional resistance has the dimensions of force, then  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$[f(x)]=\frac{F}{FL^{-2}TL}=LT^{-1}=V$ (hence, the function $f(x)$ is fluid velocity).  

2. Given $[f(x,y)]=\frac{FL^{-2}}{FL^{-1}}=L^{-1}$, then $\Big[\frac{\partial^2 \phi}{\partial x^2}\Big]=L^{-1}$ or $\Big[\frac{\partial^2\phi}{\partial y^2}\Big]=L^{-1}$ (since the terms of the Laplacian must have like dimensions). Therefore,  
$$\Big[\frac{\partial^2\phi}{\partial x^2}\Big]=L^{-1}$$
$$\frac{[\phi]}{L^2}=L^{-1}$$
$$[\phi]=L$$
3. $[\ddot{x}]=[\omega^2x]=[f(t)]$ But $\ddot{x}\equiv\frac{d^2x}{dt^2}$; therefore  
&nbsp;&nbsp;$\frac{[d^2x]}{dt^2}=\frac{L}{T^2}$ (the dimensions of acceleration). Consequently,  
&nbsp;&nbsp;$[f(t)]=LT^{-2}$, and $[\omega^2][x]=LT^{-2}$
$$[\omega^2]=T^{-2}$$
$$[\omega]=T^{-1}$$

4.
$$\rho\frac{\partial p}{\partial z}[\rho]\frac{[p]}{[z]}= ML^{-3}\frac{MLT^{-2}/L}{L}=M^2L^{-5}T^{-2}$$
$$\mu\frac{\partial^2\omega}{\partial z^2}=[\mu]\frac{[\omega]}{[z^2]}= ML^{-1}T^{-2}\frac{LT^{-1}}{L^2}=ML^{-2}T^{-2}$$
&nbsp;&nbsp;and because the equation is not dimensionally homogeneous, we conclude that it is not correctly formulated.

5.
(a) The concept of specific heat of a substance under conditions of constant pressure ($C_p$) permits of volumetric change, while the concept of specific heat of a substance under conditions of constant volume ($C_v$) permits of pressure change. In either case,
$$[C_p]=[C_v]=\frac{H}{M\Theta}$$
(b) cal$\cdot$g^-1^$\cdot$K^-1^. (calories per gram per degree Kelvin).

6.
(a)
$$q_x\hat{i}+q_y\hat{j}+q_z\hat{k}=-k\Big(\frac{\partial\theta}{\partial x}\hat{i}+\frac{\partial\theta}{\partial y}\hat{j}+ \frac{\partial\theta}{\partial z}\hat{k}\Big)$$
Because the equation must be dimensionally homogeneous in its terms, we can resolve the dimensional problem from any component. By taking the component in the x-direction,
$$[q_x]=[k]\Big[\frac{\partial\theta}{\partial x}\Big]$$
(signs have no influence on dimensions of terms)  
$\frac{H}{L^2T}=[k]\frac{\Theta}{L}$  
$[k]=\frac{H}{L\Theta T}$ (the quantity of heat transferred per unit thickness of substance per unit temperature difference per unit time).

(b) $cal\cdot cm^{-1}\cdot ^{\circ}C^{-1}\cdot sec^{-1}$  
(c) $J\cdot m^{-1}\cdot K^{-1}\cdot sec^{-1}$  
(d) Since heat is energy, then $[k]=\frac{ML^2T^{-2}}{L\Theta T}=ML\Theta^{-1}T^{-3}$  
(e) $g\cdot cm\cdot K^{-1}\cdot sec^{-3}$  
(f) $[k]=\frac{FL}{L\Theta T}=F\Theta^{-1}T^{-1}$  
(g) $nt\cdot K^{-1}\cdot sec^{-1}$  
(h) $W\cdot m^{-1}\cdot K^{-1}$  
(i) Units are $cal\cdot cm^{-1}\cdot ^{\circ}C^{-1}\cdot sec^{-1}$, $J\cdot m^{-1}\cdot K^{-1}\cdot sec^{-1}$  
Conversion chains are  
&nbsp;&nbsp;&nbsp;$H$: calorie $\rightarrow$ joule  
&nbsp;&nbsp;&nbsp;$L$: centimeter $\rightarrow$ meter  
&nbsp;&nbsp;&nbsp;$\Theta$: degree Celsius $\rightarrow$ degree Kelvin  
The identities are  
&nbsp;&nbsp;&nbsp;1 cal = 4.1840 J  
&nbsp;&nbsp;&nbsp;1 m = 100 cm  
&nbsp;&nbsp;&nbsp;1$^{\circ}C$ temp. diff. = 1K temp. diff.  
Make the obvious statement

\begin{align*}
\frac{cal}{cm\cdot ^{\circ}C\cdot sec}&=\frac{cal}{cm\cdot ^{\circ}C\cdot sec} \\
&=\frac{\rlap{-----}cal}{cm\cdot ^{\circ}C\cdot sec}\Big(\frac{4.1840 J}{\rlap{-----}cal}\Big) \\
&=\frac{1}{\rlap{-----}cm\cdot ^{\circ}C\cdot sec}\Big(\frac{4.1840J}{1}\Big)\Big(\frac{100\rlap{-----}cm}{m}\Big) \\
1\frac{cal}{cm\cdot ^{\circ}C\cdot sec}&=418.40\frac{J}{m\cdot K\cdot sec}
\end{align*}

(j) Units are $J\cdot m^{-1}\cdot K^{-1}\cdot sec^{-1}$, $g\cdot cm\cdot K^{-1} \cdot sec^{-3}$.  
Conversion chains are  
&nbsp;&nbsp;&nbsp;$H$: joule $\rightarrow$ erg $\rightarrow$ g$\cdot$cm^2^$\cdot$sec^-2^  
&nbsp;&nbsp;&nbsp;$L$: meter $\rightarrow$ centimeter  
Identities are  
&nbsp;&nbsp;&nbsp;1 J = 10^7^ erg  
&nbsp;&nbsp;&nbsp;1 erg = 1 g$\cdot$cm^2^$\cdot$sec^-2^  
&nbsp;&nbsp;&nbsp;1 m = 100 cm  

\begin{align*}
\frac{J}{m\cdot K\cdot sec}&=\frac{J}{m\cdot K \cdot sec} \\
&=\frac{J}{\rlap{---}m\cdot K\cdot sec}\Big(\frac{10^7 \rlap{-----}erg}{J}\Big)\Big(\frac{g\cdot cm^2 sec^{-2}}{\rlap{-----}erg}\Big)\Big(\frac{\rlap{---}m}{100cm}\Big) \\
1\;J\cdot m^{-1}\cdot K^{-1}\cdot sec^{-1}&=10^5g\cdot cm\cdot K^{-1}\cdot sec^{-3}
\end{align*}


7.

\begin{align*}
1 ft&=\frac{1}{3}yd \\
&=\frac{1}{3}(0.9144 m) \\
&=\frac{1}{3}(0.9144)(100cm) \\
r&=1.5ft=1.5\Big(\frac{1}{3}(0.9144)(100cm)\Big) \\
vol&=\frac{4}{3}\pi r^3 \\
&= \frac{4\pi}{3}\Big((1.5)\frac{1}{3}(0.9144)(100cm)\Big)^3 \\
&=400320cm^3
\end{align*}

8. Identities are $1L=10^3cm^3$, $1mL=10^{-3}L$.  
The dimensional concept of cubical density is
$$\mbox{density}=\frac{\mbox{mass}}{\mbox{volume}}$$
and for the problem
$$0.79g\cdot cm^{-3} = \frac{\mbox{mass (of 30 m alc.)}}{30 mL}$$
Therefore,
\begin{align*}
\mbox{mass (of 30 mL of alc)}&=(0.79g\cdot cm^{-3})\cdot(30mL) \\
&=\Big(\frac{0.79g}{\rlap{-----}cm^3}\Big)\frac{30\rlap{-----}mL}{1}\Big(\frac{10^{-3}L}{\rlap{-----}mL}\Big)\Big(\frac{10^3\rlap{-----}cm^3}{\rlap{---}L}\Big) \\
&= 23.7g
\end{align*}

9. Pressure is force per unit area.  
The area ($L^2$) is 15 cm $\times$ 2.8 mm.  
The force ($M\cdot LT^{-2}$) is 150 lb $\times$ 980 cm$\cdot$sec^-2^.  
If we employ the cgs system of units, the conversion identities are  

 *  1 mm = 10^-3^ m  
 *  1 m = 10^2^ cm  
 *  1 lb = 0.4536 kg  
 *  1 kg=10^3^ g
 
\begin{align*}
p&=F\cdot A^{-1} \\
&=\Big(\frac{150lb}{1}\cdot\frac{980cm}{sec^2}\Big)\Big(\frac{1}{15\rlap{-----}cm}\Big) \\
&=\frac{150\rlap{---}lb}{1}\Big(\frac{0.4536\rlap{---}kg}{\rlap{---}lb}\Big)\Big(\frac{10^3g}{\rlap{---}kg}\Big)\frac{980}{sec^2}\Big(\frac{1}{15}\Big)\frac{1}{2.8\rlap{-----}mm}\Big(\frac{\rlap{-----}mm}{10^{-3}\rlap{---}m}\Big)\Big(\frac{\rlap{---}m}{10^2cm}\Big) \\
&=15,876,000 g\cdot cm^{-1}\cdot sec^{-2}
\end{align*}


In keeping with the concept of pressure as force per unit area, we can also write the pressure unit $g\cdot cm^{-l}\cdot sec^{-2}$ as
$$\frac{g}{cm\cdot sec^2}\cdot\frac{cm}{cm}=\frac{g\cdot cm\cdot sec^{-2}}{cm^2}=\frac{dyne}{cm^2}$$
Hence the pressure on the ice can also be written
$$p=15,876,000 \;dyn\cdot cm^{-2}$$
On the other hand, the mass concentration (mass per unit area) is simply  
\begin{align*}
\frac{\mbox{mass}}{\mbox{area}}&=\frac{150lb}{15cm\times 2.8mm} \\
&=230.4\;lb/in^2 \\
&=16200\;g/cm^2
\end{align*}

10. For pressure in cgs units, the needed conversion identities are

 *  1 $\mu$m = 10^-6^ m
 *  1 $\mu$m^2^ = 10^-12^ m^2^
 *  1 m = 10^2^ cm
 *  1 m^2^ = 10^4^ cm^2^
 *  16 oz = 1 lb
 *  1 lb = 0.4536 kg
 *  1 kg = 10^3^ g

\begin{align*}
A&=\pi r^2 = \pi(40\mu m)^2 = \pi\cdot 1600\mu m^2 \\
p&=F\cdot A^{-1} = (2oz)(980cm\cdot sec^{-2})\Big(\frac{1}{\pi\cdot 1600\mu m^2}\Big) \\
&=\frac{2\rlap{---}oz}{1}\Big(\frac{\rlap{---}lb}{16\rlap{---}oz}\Big)\Big(\frac{0.4536\rlap{---}kg}{\rlap{---}lb}\Big)\Big(\frac{10^3g}{\rlap{---}kg}\Big)\Big(\frac{980cm}{sec^2}\Big)\frac{1}{\pi\cdot 1600\rlap{---}\mu m^2}\Big(\frac{\rlap{----}\mu m^2}{10^{-12}\rlap{---}m^2}\Big)\Big(\frac{\rlap{---}m^2}{10^4cm^2}\Big) \\
&=1.105\times 10^9\;dyn\cdot cm^{-2}
\end{align*}


## References {#dimmethods-references}
Gray, D.E. (1972) Handbook of the American Journal of Physics, 3rd ed. McGraw-Hill, N.Y.

National Bureau of Standards (1968) The English and metric systems of measurement, NBS Special Publ. 304A.

National Bureau of Standards (1964) NBS International System, Tech. News Bull. 48.
